languages:
  JavaScript: true
engines:
  eslint:
    enabled: true
    channel: "eslint-3"
    version: 3
    config:
      config: .eslintrc.yaml
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - src/**/*.js
  - test/**/*.js

exclude_paths:
- "node_modules/**"
- "lib/**"
