engines:
  eslint:
    enabled: true
    config:
      config: .eslintrc.yaml
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - lib/**/.js
exclude_paths:
- "node_modules/**"
- "dist/**"
- "test/phantomjs/**"
